name: faenet
act: swish
loss: mae
hidden_channels: 384 #384
num_filters: 480 # 480
num_interactions: 6
num_gaussians: 1 # 104
dropout_edge: 0.0
cutoff: 6.0
second_layer_MLP: true
mp_type: base  # Message Passing type {'base', 'simple', 'updownscale', 'updownscale_base'}
graph_norm: True
complex_mp: True  # 2-layer MLP in Interaction blocks
disp_output_dim: 3
N_output_dim: 18
M_output_dim: 18 
regress_forces: direct # direct_with_gradient_target
force_decoder_type: "res" # force head (`"simple"`, `"mlp"`, `"res"`, `"res_updown"`)
force_decoder_model_config:
  simple:
    hidden_channels: 128
    norm: batch1d # batch1d, layer or null
  mlp:
    hidden_channels: 384   ## 256 ou 384?
    norm: batch1d # batch1d, layer or null
  res:
    hidden_channels: 600 # 384  ## 128 ou 384?
    norm: batch1d # batch1d, layer or null
  res_updown:
    hidden_channels: 384 ## 128 ou 384?
    norm: batch1d # batch1d, layer or null