name: faenet
act: swish
loss: mae
hidden_channels: 384
num_filters: 480
num_interactions: 5
num_gaussians: 1 # 104
dropout_lin: 0.0
dropout_edge: 0.0
cutoff: 6.0
use_pbc: True
tag_hidden_channels: 64 # only for OC20
pg_hidden_channels: 64 # period & group embedding hidden channels
phys_embeds: True # physics-aware embeddings for atoms
disp_output_dim: 3
N_output_dim: 18
M_output_dim: 18 
regress_forces: direct # direct_with_gradient_target
force_decoder_type: "res" # force head (`"simple"`, `"mlp"`, `"res"`, `"res_updown"`)
force_decoder_model_config:
  simple:
    hidden_channels: 128
    norm: batch1d # batch1d, layer or null
  mlp:
    hidden_channels: 384   ## 256 ou 384?
    norm: batch1d # batch1d, layer or null
  res:
    hidden_channels: 128
    norm: batch1d # batch1d, layer or null
  res_updown:
    hidden_channels: 128
    norm: batch1d # batch1d, layer or null