name: blocks_random_3x6x3_1000
oc20: false
save_model_path: models/blocks_random_3x6x3_1000/model_blocks_random_3x6x3_1000.pth
train:
  normalize_labels: true
  src: data/blocks_random_3x6x3_1000/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 24.865097045898438
  target_std_N: 19.85453224182129
  target_std_disp: 0.014184501022100449
val:
  val:
    src: data/blocks_random_3x6x3_1000/val/val.lmdb
