name: blocks_unique_random_last_floor_2x2x2_10
oc20: false
save_model_path: models/blocks_unique_random_last_floor_2x2x2_10/model_blocks_unique_random_last_floor_2x2x2_10.pth
save_preds_path: models/blocks_unique_random_last_floor_2x2x2_10/val/
save_transformed_base_path: models/blocks_unique_random_last_floor_2x2x2_10/val/transformed_base/
save_transformed_preds_path: models/blocks_unique_random_last_floor_2x2x2_10/val/transformed_predictions/
train:
  normalize_labels: true
  src: data/blocks_unique_random_last_floor_2x2x2_10/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 28.599302291870117
  target_std_N: 49.06037139892578
  target_std_disp: 0.008243716321885586
val:
  src: data/blocks_unique_random_last_floor_2x2x2_10/val/val.lmdb
  val:
    src: data/blocks_unique_random_last_floor_2x2x2_10/val/val.lmdb
