name: box_unique_random_contour_3x4x3_1000
oc20: false
save_model_path: models/box_unique_random_contour_3x4x3_1000/model_box_unique_random_contour_3x4x3_1000.pth
train:
  normalize_labels: true
  src: data/box_unique_random_contour_3x4x3_1000/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 42.242610931396484
  target_std_N: 56.589080810546875
  target_std_disp: 0.024156810715794563
val:
  val:
    src: data/box_unique_random_contour_3x4x3_1000/val/val.lmdb
