name: boxes_random_contour_pm_4x4x4_10000
oc20: false
save_model_path: models/boxes_random_contour_pm_4x4x4_10000/model_boxes_random_contour_pm_4x4x4_10000.pth
save_preds_path: models/boxes_random_contour_pm_4x4x4_10000/val/
save_transformed_base_path: models/boxes_random_contour_pm_4x4x4_10000/val/transformed_base/
save_transformed_preds_path: models/boxes_random_contour_pm_4x4x4_10000/val/transformed_predictions/
train:
  normalize_labels: true
  src: data/boxes_random_contour_pm_4x4x4_10000/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 26.830305099487305
  target_std_N: 27.27349853515625
  target_std_disp: 0.015821222215890884
val:
  src: data/boxes_random_contour_pm_4x4x4_10000/val/val.lmdb
  val:
    src: data/boxes_random_contour_pm_4x4x4_10000/val/val.lmdb
