name: boxes_random_contour_4x4x4_2500
oc20: false
save_model_path: models/boxes_random_contour_4x4x4_2500/model_boxes_random_contour_4x4x4_2500.pth
save_preds_path: models/boxes_random_contour_4x4x4_2500/val/
save_transformed_base_path: models/boxes_random_contour_4x4x4_2500/val/transformed_base/
save_transformed_preds_path: models/boxes_random_contour_4x4x4_2500/val/transformed_predictions/
train:
  normalize_labels: true
  src: data/boxes_random_contour_4x4x4_2500/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 53.796112060546875
  target_std_N: 60.91417694091797
  target_std_disp: 0.030852848663926125
val:
  src: data/boxes_random_contour_4x4x4_2500/val/val.lmdb
  val:
    src: data/boxes_random_contour_4x4x4_2500/val/val.lmdb
