name: structures
oc20: false
train:
  normalize_labels: true
  src: data/regular_gw_3x6x3/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 1882.2244873046875
  target_std_N: 35.642982482910156
  target_std_disp: 0.03276753053069115
val:
  val:
    src: data/regular_gw_3x6x3/val/val.lmdb
