name: structures
oc20: false
train:
  normalize_labels: true
  src: data/regular_random_3x4x3/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 13.24117374420166
  target_std_N: 0.162573903799057
  target_std_disp: 0.00010741333244368434
val:
  val:
    src: data/regular_random_3x4x3/val/val.lmdb
