name: oc20
train:
    src: data/is2re/train/is2re_10k.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
val:
    val_id:
        src: data/is2re/val/val_id.lmdb
    val_ood_both:
        src: data/is2re/val/val_ood_both.lmdb
oc20: True # whether the oc20 dataset is used or not