name: structures
oc20: false
train:
  normalize_labels: true
  src: data/regular_random_3x6x3/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 15.021737098693848
  target_std_N: 6.083912372589111
  target_std_disp: 0.00430138036608696
val:
  val:
    src: data/regular_random_3x6x3/val/val.lmdb
