name: regular_random_3x7x3_1
oc20: false
'mode': 'predict'
pretrained_model_path: 'models/regular_random_3x7x3_2000.pth'
pred:
  normalize_labels: true
  src: data/regular_random_3x7x3_1/pred/pred.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 15.20159912109375
  target_std_N: 4.858945369720459
  target_std_disp: 0.002471183892339468
