name: structures
oc20: false
train:
  normalize_labels: true
  src: data/regular_gw_2x6x2/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 1100.0054931640625
  target_std_N: 41.71244430541992
  target_std_disp: 0.03976190462708473
val:
  val:
    src: data/regular_gw_2x6x2/val/val.lmdb
