name: structures
oc20: false
train:
  normalize_labels: true
  src: data/regular_w_4x10x4/train/train.lmdb
  target_mean_M: 0
  target_mean_N: 0
  target_mean_disp: 0
  target_std_M: 65.70781707763672
  target_std_N: 57.86106872558594
  target_std_disp: 0.08666791766881943
val:
  val:
    src: data/regular_w_4x10x4/val/val.lmdb
