name: structures
train:
    src: data/regular_random_gw/train/train.lmdb
    # normalize_labels: True
    # target_mean: -1.525913953781128
    # target_std: 2.279365062713623
val:
    val:
        src: data/regular_random_gw/val/val.lmdb

# oc20: True
oc20: False # whether the oc20 dataset is used or not