run_name: "default"

logger: comet
project: faetec
debug: False  # log or not

equivariance: "" # "" or "data_augmentation" or "frame_averaging"  ################################################### OFF for now // réactiver faenet plus tard
fa_type: "stochastic" # "" or "stochastic" or "full"

optimizer:
    batch_size: 16 # number of structures per batch
    eval_batch_size: 8
    epochs: 15
    scheduler: CosineAnnealingLR
    optimizer: AdamW
    lr_initial: 0.002

defaults:
    - _self_
    - dataset : box_unique_random_3x3x3_1000 # <-- Default dataset; it can be overridden
    - model : faenet
  
# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .